### ISSUE TITLE
imba -w server.imba fails

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba-base-template#2]
I see the following failure when running `npm run start`

```
➜ ./node_modules/.bin/imba --version
2.0.0-alpha.129
imba-base-template on  master via ⬢ v13.14.0 took 2s 
➜ npm run start         

> imba-base-template@ start /Users/ccscanf/src/github.com/imba/imba-base-template
> imba -w server.imba

ℹ building in /var/folders/8g/2c1svrw91gj6f6mtngz3m_vm0000gp/T/tmp-88356-ZFTKDQtkKz6B
✔ write server.js 34.2kb
✔ write public/index.html 0.5kb
✔ write public/__assets__/logo.4MXEBDEU.svg 4.5kb
✔ write public/__assets__/app/client.MABRH81D.js.map 54.7kb
✔ write public/__assets__/app/client.MABRH81D.js 37.5kb
✔ write public/__assets__/app/client.JHAIMZ9V.css 0.3kb
✔ write server.js.manifest 15.6kb
✔ write server.loader.js 9.3kb
ℹ finished in 356ms - 44.19mb
ℹ server.imba: starting
/Users/ccscanf/src/github.com/imba/imba-base-template/server.imba:719
    if (this.meta?.content) {
                  ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.import_module.Module._extensions.<computed> (/Users/ccscanf/src/github.com/imba/imba-base-template/node_modules/imba/loader.imba.js:319:16)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:869:16)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
× server.imba: exited with error code: 1
```

**Comment by aalemayhu** [comment]
@somebee could you take a look at this? Thanks 🙏🏾

**Comment by codeluggage** [comment]
Following up on this with more details - I have no issues with RC 165 in https://github.com/imba/imba-base-template/pull/4

If you have a moment @aalemayhu, could you see if the issue is still happening on your machine with that version?

**Comment by aalemayhu** [comment]
Yes, this has been resolved. Thanks!
